# Databricks App Configuration
# This file defines how the app should run in Databricks Apps

# App metadata
name: "Danone Onesource 2.0 assistant"
version: "1.0.0"
description: "AI-powered assistant with Onesource documentation"

# Execution configuration
execution:
  # Main entry point - use the Databricks-optimized main file
  command: "python main_databricks.py"
  
  # Environment variables
  env:
    # Databricks configuration
    DATABRICKS_HOST: "https://fe-vm-vdm-serverless-nmmvdg.cloud.databricks.com"
    DATABRICKS_ENDPOINT: "https://fe-vm-vdm-serverless-nmmvdg.cloud.databricks.com/serving-endpoints/databricks-gpt-oss-20b/invocations"
    
    # Database configuration (will use mock mode in Databricks)
    DATABASE_TYPE: "mock"
    
    # Server configuration
    HOST: "0.0.0.0"
    PORT: "8000"
    
    # Logging
    LOG_LEVEL: "INFO"

# Resource limits (Databricks Apps constraints)
resources:
  # Maximum 2 vCPUs and 6GB memory
  cpu: 2
  memory: "6Gi"

# Dependencies
dependencies:
  # Use the requirements.txt file for Python packages
  requirements_file: "requirements-databricks.txt"

# Health check configuration
health_check:
  # Health check endpoint
  endpoint: "/health"
  # Initial delay before health checks start
  initial_delay_seconds: 30
  # How often to check
  period_seconds: 10
  # Timeout for each check
  timeout_seconds: 5
  # Number of failures before marking as unhealthy
  failure_threshold: 3
  # Number of successes before marking as healthy
  success_threshold: 1

# App settings
settings:
  # Enable auto-scaling (if supported)
  auto_scale: false
  # Enable logs
  enable_logs: true
  # Log retention (in days)
  log_retention_days: 7
