command: [
  "python",
  "main_databricks.py"
]

env:
  - name: "SERVING_ENDPOINT"
    value: "ka-1f9efcb2-endpoint"
  - name: "DATABRICKS_WORKSPACE_URL"
    value: "https://fe-vm-vdm-serverless-nmmvdg.cloud.databricks.com"
  - name: "LAKEBASE_HOST"
    value: "instance-cc424808-7c73-4954-af28-539b992b0587.database.cloud.databricks.com"
  - name: "LAKEBASE_PORT"
    value: "5432"
  - name: "LAKEBASE_DATABASE_NAME"
    value: "danone-pg-db"
  - name: "LAKEBASE_USERNAME"
    value: "christophe.anglade@databricks.com"
  - name: "LAKEBASE_PASSWORD"
    value: "your-lakebase-password-here"
  - name: "DB_POOL_SIZE"
    value: "5"
  - name: "DB_MAX_OVERFLOW"
    value: "10"
  - name: "DB_COMMAND_TIMEOUT"
    value: "30"
  - name: "DB_POOL_TIMEOUT"
    value: "10"
  - name: "DB_POOL_RECYCLE_INTERVAL"
    value: "3600"