command: [
  "python",
  "main_databricks.py"
]

env:
  - name: "SERVING_ENDPOINT"
    value: "ka-1f9efcb2-endpoint"
  - name: "DATABRICKS_WORKSPACE_URL"
    value: "https://fe-vm-vdm-serverless-nmmvdg.cloud.databricks.com"
  
  # Lakebase connection settings
  - name: "LAKEBASE_INSTANCE_NAME"
    value: "onesource-chatbot-pg"
  - name: "LAKEBASE_DATABASE_NAME"
    value: "databricks_postgres"
  - name: "DATABRICKS_DATABASE_PORT"
    value: "5432"
  
  # Additional Lakebase settings
  - name: "LAKEBASE_HOST"
    value: "instance-99e23c55-87b3-4523-b353-1e83fb0a0249.database.azuredatabricks.net"
  
  # Database connection pool settings
  - name: "DB_POOL_SIZE"
    value: "5"
  - name: "DB_MAX_OVERFLOW"
    value: "10"
  - name: "DB_COMMAND_TIMEOUT"
    value: "30"
  - name: "DB_POOL_TIMEOUT"
    value: "10"
  - name: "DB_POOL_RECYCLE_INTERVAL"
    value: "3600"